### ISSUE TITLE
Old links on the high score page

### ISSUE THREAD

**Issue by jack-lewin** [jack-lewin/github-high-scores#1]
In the h2 title: `user >> github-high-scores >> high scores`
- User link doesn't work, e.g. http://gitscore.herokuapp.com/jack-lewin
- The second and third links both point to the same page

Proposed solution:
- User link is the owners's GitHub profile
- Second link is to the current page, e.g. http://gitscore.herokuapp.com/jack-lewin/github-high-scores
- Third link (`high scores`) is no longer a link

Does that sound reasonable @leereilly?

**Comment by leereilly** [comment]
That sounds good to me @jack-lewin :metal:
